import { ReactNode, useEffect, VFC } from 'react'
import Head from 'next/head'
import { Header } from 'components/Header'
import { onAuthStateChanged } from 'firebase/auth'
import { useResetRecoilState, useSetRecoilState } from 'recoil'
import { loginUserState } from 'store/auth'
import { auth } from 'utils/firebase'

type Props = {
  children: ReactNode
}

const Layout: VFC<Props> = (props) => {
  const { children } = props

  const setLoginUser = useSetRecoilState(loginUserState)
  const resetStatus = useResetRecoilState(loginUserState)

  useEffect(() => {
    onAuthStateChanged(auth, (user) => {
      if (user != null) {
        const uid = user.uid
        setLoginUser(uid)
      } else {
        resetStatus()
      }
    })
  }, [resetStatus, setLoginUser])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Icon.svg" />
      </Head>
      <main>
        <Header />
        <div className="py-10 h-[calc(100vh-64px)] bg-gray-200">{children}</div>
      </main>
    </>
  )
}

export default Layout
