import { ReactNode, useEffect, VFC, useState } from 'react'
import Head from 'next/head'
import { Header } from 'components/Header'
import { useRecoilValue } from 'recoil'
import { loginUserState } from 'store/auth'

type Props = {
  children: ReactNode
  layout: string
}

const Layout: VFC<Props> = (props) => {
  const { children, layout } = props
  const [isLoaded, setIsLoaded] = useState<boolean>(false)
  const userState = useRecoilValue(loginUserState)

  useEffect(() => {
    if (userState.uid !== null) {
      setIsLoaded(true)
    }
  }, [userState, setIsLoaded])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Icon.svg" />
      </Head>
      <main>
        {isLoaded ? (
          <>
            <Header />
            <div
              className={`py-10 bg-gray-200
                ${layout === 'normal' ? 'h-[calc(100vh-64px)]' : ''}`}
            >
              {children}
            </div>
          </>
        ) : (
          <></>
        )}
      </main>
    </>
  )
}

export default Layout
