import { ReactNode, useEffect, VFC } from 'react'
import Head from 'next/head'
import { Header } from 'components/Header'

type Props = {
  children: ReactNode
  layout: string
}

const Layout: VFC<Props> = (props) => {
  const { children, layout } = props

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Icon.svg" />
      </Head>
      <main>
        <Header />
        <div
          className={`py-10 bg-gray-200
            ${layout === 'normal' ? 'h-[calc(100vh-64px)]' : ''}`}
        >
          {children}
        </div>
      </main>
    </>
  )
}

export default Layout
