import { ReactNode } from 'react'
import Head from "next/head";
import { Header } from "components/Header";

interface Props {
  children: ReactNode
}

export default function Layout({ children }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Icon.svg" />
      </Head>
      <main>
        <Header />
        {children}
      </main>
    </>
  )
}