import { ReactNode, VFC } from "react";
import Head from "next/head";
import { Header } from "components/Header";

type Props = {
  children: ReactNode;
};

const Layout: VFC<Props> = (props) => {
  const { children } = props;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Icon.svg" />
      </Head>
      <main>
        <Header />
        <div className="py-10">{children}</div>
      </main>
    </>
  );
};

export default Layout;
